Instance: EPathRepositoryServerCapabilityStatement
InstanceOf: CapabilityStatement
Usage: #definition
* url = "http://e-path.jp/fhir/ePath/CapabilityStatement/EPathRepositoryServerCapabilityStatement"
* name = "EPathRepositoryServerCapabilityStatement"
* title = "EPath Repository Server CapabilityStatement"
* status = #active
* experimental = false
* date = "2025-11-07"
* description = "ePath R4 実装ガイドを利用したePathリポジトリを作成する際にサーバ側で規定するCapabilityStatementのOperationsおよびSearch Parametersのリスト例を提示する。ePath R4 実装ガイドがサポートするFHIRプロファイルに限定しているため、FHIR Baseのプロファイルを利用する際などは必要な項目を追記すること。"
* kind = #requirements
* instantiates = "http://e-path.jp/fhir/ePath/CapabilityStatement/EPathRepositoryServerCapabilityStatement"
* fhirVersion = #4.0.1
* format[0] = #xml
* format[+] = #json
* rest.mode = #server

// Patient
* rest.resource[0].type = #Patient
* rest.resource[=].supportedProfile[0] = "http://e-path.jp/fhir/ePath/StructureDefinition/EPathPatient"
* rest.resource[=].supportedProfile[+] = "http://jpfhir.jp/fhir/core/StructureDefinition/JP_Patient"
* rest.resource[=].interaction[0].code = #create
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].referencePolicy = #resolves
* rest.resource[=].searchRevInclude = "Provenance:target"
* rest.resource[=].searchParam[0].name = "identifier"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Patient-identifier"
* rest.resource[=].searchParam[=].type = #token
* rest.resource[=].searchParam[=].documentation = "患者IDを指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "name"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Patient-name"
* rest.resource[=].searchParam[=].type = #string
* rest.resource[=].searchParam[=].documentation = "患者氏名を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "family"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/individual-family"
* rest.resource[=].searchParam[=].type = #string
* rest.resource[=].searchParam[=].documentation = "患者姓を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "given"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/individual-given"
* rest.resource[=].searchParam[=].type = #string
* rest.resource[=].searchParam[=].documentation = "患者名を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "birthdate"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/individual-birthdate"
* rest.resource[=].searchParam[=].type = #date
* rest.resource[=].searchParam[=].documentation = "生年月日を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "gender"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/individual-gender"
* rest.resource[=].searchParam[=].type = #token
* rest.resource[=].searchParam[=].documentation = "性別を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "organization"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Patient-organization"
* rest.resource[=].searchParam[=].type = #reference
* rest.resource[=].searchParam[=].documentation = "パスが適用された患者の所属する施設を指定して検索するために使用するパラメータ"

// Organization
* rest.resource[+].type = #Organization
* rest.resource[=].supportedProfile = "http://e-path.jp/fhir/ePath/StructureDefinition/EPathOrganization"
* rest.resource[=].supportedProfile[+] = "http://jpfhir.jp/fhir/core/StructureDefinition/JP_Organization"
* rest.resource[=].interaction[0].code = #create
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].referencePolicy = #resolves
* rest.resource[=].searchRevInclude = "Provenance:target"
* rest.resource[=].searchParam[0].name = "identifier"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Organization-identifier"
* rest.resource[=].searchParam[=].type = #token
* rest.resource[=].searchParam[=].documentation = "施設の識別子を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "name"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Organization-name"
* rest.resource[=].searchParam[=].type = #string
* rest.resource[=].searchParam[=].documentation = "施設名を指定して検索するために使用するパラメータ"

// Bundle
* rest.resource[+].type = #Bundle
* rest.resource[=].supportedProfile[0] = "http://e-path.jp/fhir/ePath/StructureDefinition/EPathBundleMessageEP01"
* rest.resource[=].supportedProfile[+] = "http://e-path.jp/fhir/ePath/StructureDefinition/EPathBundleMessageEP02"
* rest.resource[=].supportedProfile[+] = "http://e-path.jp/fhir/ePath/StructureDefinition/EPathBundleMessageEP12"
* rest.resource[=].supportedProfile[+] = "http://e-path.jp/fhir/ePath/StructureDefinition/EPathBundleMessageEP22"
* rest.resource[=].interaction[0].code = #create
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].referencePolicy = #resolves
* rest.resource[=].searchRevInclude = "Provenance:target"
* rest.resource[=].searchParam[0].name = "identifier"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Bundle-identifier"
* rest.resource[=].searchParam[=].type = #token
* rest.resource[=].searchParam[=].documentation = "識別子を指定して検索するために使用するパラメータ"

// List
* rest.resource[+].type = #List
* rest.resource[=].supportedProfile[0] = "http://e-path.jp/fhir/ePath/StructureDefinition/EPathListEPathRepository"
* rest.resource[=].interaction[0].code = #create
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].referencePolicy = #resolves
* rest.resource[=].searchRevInclude = "Provenance:target"
* rest.resource[=].searchParam[0].name = "code"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/clinical-code"
* rest.resource[=].searchParam[=].type = #token
* rest.resource[=].searchParam[=].documentation = "用途（eWSなど）指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "date"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/clinical-date"
* rest.resource[=].searchParam[=].type = #date
* rest.resource[=].searchParam[=].documentation = "パス適用開始日指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "identifier"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/clinical-identifier"
* rest.resource[=].searchParam[=].type = #token
* rest.resource[=].searchParam[=].documentation = "適用後パス識別子を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "patient"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/clinical-patient"
* rest.resource[=].searchParam[=].type = #reference
* rest.resource[=].searchParam[=].documentation = "患者を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "status"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/List-status"
* rest.resource[=].searchParam[=].type = #token
* rest.resource[=].searchParam[=].documentation = "ePathリポジトリで管理されている適用後パスデータの状態を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "ep-pathcode"
* rest.resource[=].searchParam[=].definition = "http://e-path.jp/fhir/ePath/SearchParameter/EPathListPathCodeSearchParameter"
* rest.resource[=].searchParam[=].type = #uri
* rest.resource[=].searchParam[=].documentation = "ePathリポジトリをパスコードを指定して検索するために使用するパラメータ"

// Questionnaire
* rest.resource[+].type = #Questionnaire
* rest.resource[=].supportedProfile[0] = "http://e-path.jp/fhir/ePath/StructureDefinition/EPathQuestionnaire"
* rest.resource[=].interaction[0].code = #create
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].referencePolicy = #resolves
* rest.resource[=].searchRevInclude = "Provenance:target"
* rest.resource[=].searchParam[0].name = "identifier"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Questionnaire-identifier"
* rest.resource[=].searchParam[=].type = #token
* rest.resource[=].searchParam[=].documentation = "識別子を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "url"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Questionnaire-url"
* rest.resource[=].searchParam[=].type = #uri
* rest.resource[=].searchParam[=].documentation = "入力フォームの正規URLを指定して検索するために使用するパラメータ"

// QuestionnaireResponse
* rest.resource[+].type = #QuestionnaireResponse
* rest.resource[=].supportedProfile[0] = "http://e-path.jp/fhir/ePath/StructureDefinition/EPathQuestionnaireResponse"
* rest.resource[=].interaction[0].code = #create
* rest.resource[=].interaction[+].code = #search-type
* rest.resource[=].interaction[+].code = #read
* rest.resource[=].interaction[+].code = #vread
* rest.resource[=].interaction[+].code = #update
* rest.resource[=].interaction[+].code = #patch
* rest.resource[=].interaction[+].code = #delete
* rest.resource[=].interaction[+].code = #history-instance
* rest.resource[=].interaction[+].code = #history-type
* rest.resource[=].referencePolicy = #resolves
* rest.resource[=].searchRevInclude = "Provenance:target"
* rest.resource[=].searchParam[0].name = "authored"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/QuestionnaireResponse-authored"
* rest.resource[=].searchParam[=].type = #date
* rest.resource[=].searchParam[=].documentation = "回答を記述した日時を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "identifier"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/Questionnaire-identifier"
* rest.resource[=].searchParam[=].type = #token
* rest.resource[=].searchParam[=].documentation = "識別子を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "patient"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/QuestionnaireResponse-patient"
* rest.resource[=].searchParam[=].type = #reference
* rest.resource[=].searchParam[=].documentation = "患者を指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "questionnaire"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/QuestionnaireResponse-questionnaire"
* rest.resource[=].searchParam[=].type = #reference
* rest.resource[=].searchParam[=].documentation = "回答に対応する入力フォームを指定して検索するために使用するパラメータ"
* rest.resource[=].searchParam[+].name = "status"
* rest.resource[=].searchParam[=].definition = "http://hl7.org/fhir/SearchParameter/QuestionnaireResponse-status"
* rest.resource[=].searchParam[=].type = #token
* rest.resource[=].searchParam[=].documentation = "回答の状態を指定して検索するために使用するパラメータ"