CodeSystem: EPathTaskCategoryLv2CS
Id: EPathTaskCategoryLv2CS
Title: "EPath TaskCategory Lv2 CS"
Description: "タスク分類（第２階層）"
* ^identifier.system = "urn:ietf:rfc:3986"
* ^identifier.value = "urn:oid:1.2.392.200250.2.2.50.150.2"
* ^version = "1.0.0"
* ^status = #active
* ^experimental = false
* ^date = "2024-10-24"
* ^publisher = "ePath Project"
* ^contact.name = "ePath Project"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "https://e-path.jp"
* ^jurisdiction = urn:iso:std:iso:3166#JP
* ^caseSensitive = true
* ^content = #complete
* #TPPR "処方"
* #TPIN "注射"
* #TPRE "レジメン"
* #TPTR "処置"
* #TPOP "手術"
* #TPBT "輸血"
* #TPRH "リハビリ"
* #TPDI "透析"
* #TPRT "放射線治療"
* #TPCI "条件付き指示（必要時・対症）"
* #EXSP "検体検査"
* #EXMB "細菌検査"
* #EXPH "生理検査"
* #EXEN "内視鏡検査"
* #EXIM "画像診断"
* #EXPA "病理診断"
* #MLBR "朝"
* #MLLU "昼"
* #MLSU "夕"
* #NC01 "清潔ケア"
* #NC02 "整容・更衣ケア"
* #NC03 "栄養・食事ケア"
* #NC04 "排泄ケア"
* #NC05 "起居動作支援"
* #NC06 "移動ケア"
* #NC07 "安全ケア"
* #NC08 "睡眠ケア"
* #NC09 "苦痛の予防・軽減ケア"
* #NC10 "呼吸ケア"
* #NC11 "循環ケア"
* #NC12 "病床・室内環境ケア"
* #NC13 "意思疎通ケア"
* #NC14 "発育・発達ケア"
* #NC15 "心理的ケア"
* #NC16 "リフレッシュケア"
* #NC17 "行動制限時のケア"
* #EGNC "栄養指導"
* #EGCS "指導"
* #EGIC "IC"
* #EGEP "看護Eプラン"